apiVersion: mysql.sql.m.crossplane.io/v1alpha1
kind: Database
metadata:
  name: example-db
  namespace: default
spec:
  forProvider: {}
  providerConfigRef:
    kind: ProviderConfig
    name: default
