apiVersion: mysql.sql.m.crossplane.io/v1alpha1
kind: Database
metadata:
  name: example-db
  namespace: default
spec:
  forProvider:
    # Optional: set the default character set for the database
    defaultCharacterSet: utf8mb4
    # Optional: set the default collation for the database
    defaultCollation: utf8mb4_bin
  providerConfigRef:
    kind: ProviderConfig
    name: default
