apiVersion: mysql.sql.m.crossplane.io/v1alpha1
kind: Grant
metadata:
  name: example-grant-all-databases
  namespace: default
spec:
  forProvider:
    privileges:
      - DROP
      - CREATE ROUTINE
      - EVENT
    userRef:
      name: example-user
