apiVersion: mysql.sql.m.crossplane.io/v1alpha1
kind: Grant
metadata:
  name: example-grant-table
  namespace: default
spec:
  forProvider:
    privileges:
      - DROP
      - INSERT
      - SELECT
      - UPDATE (status, updated_at)
    table: example-table
    userRef:
      name: example-user
    databaseRef:
      name: example-db
  providerConfigRef:
    kind: ProviderConfig
    name: default