apiVersion: mssql.sql.m.crossplane.io/v1alpha1
kind: User
metadata:
  name: example-user
  namespace: default
spec:
  forProvider:
    databaseRef:
      name: example-db
    passwordSecretRef:
      name: example-pw
      namespace: default
      key: password
  writeConnectionSecretToRef:
    name: example-connection-secret
    namespace: default
