apiVersion: mssql.sql.m.crossplane.io/v1alpha1
kind: User
metadata:
  name: example-user
  namespace: default
spec:
  providerConfigRef:
    kind: ProviderConfig
    name: default
  forProvider:
    databaseRef:
      name: example-db
    passwordSecretRef:
      name: example-pw
      key: password
  writeConnectionSecretToRef:
    name: example-connection-secret
