apiVersion: postgresql.sql.crossplane.io/v1alpha1
kind: Database
metadata:
  name: example
spec:
  forProvider: {}
---
apiVersion: postgresql.sql.crossplane.io/v1alpha1
kind: Database
metadata:
  name: db1
spec:
  deletionPolicy: Orphan
  forProvider:
    allowConnections: true
    owner: "ownerrole"