apiVersion: postgresql.sql.crossplane.io/v1alpha1
kind: Extension
metadata:
  name: hstore-extension-db
spec:
  forProvider:
    extension: hstore
    version: "1.4"
    databaseRef:
      name: example
  providerConfigRef:
    name: default
---
apiVersion: postgresql.sql.crossplane.io/v1alpha1
kind: Extension
metadata:
  name: ltree-extension-db
spec:
  forProvider:
    extension: ltree
    version: "1.1"
    databaseRef:
      name: example
  providerConfigRef:
    name: default
