apiVersion: postgresql.sql.crossplane.io/v1alpha1
kind: Grant
metadata:
  name: example-grant-role-1-on-database
spec:
  forProvider:
    privileges:
      - CREATE
    withOption: GRANT
    roleRef:
      name: example-role
    databaseRef:
      name: example
---
apiVersion: postgresql.sql.crossplane.io/v1alpha1
kind: Grant
metadata:
  name: example-grant-role-2-on-database
spec:
  forProvider:
    privileges:
      - CONNECT
      - TEMPORARY
    roleRef:
      name: example-role
    databaseRef:
      name: example
---
apiVersion: postgresql.sql.crossplane.io/v1alpha1
kind: Grant
metadata:
  name: example-grant-role-membership
spec:
  forProvider:
    withOption: ADMIN
    roleRef:
      name: example-role
    memberOfRef:
      name: parent-role
---
apiVersion: postgresql.sql.crossplane.io/v1alpha1
kind: Grant
metadata:
  name: grant-postgres-an-owner-role
spec:
  deletionPolicy:  Orphan
  forProvider:
    role: "postgres"
    memberOfRef:
      name: "ownerrole"
---
apiVersion: postgresql.sql.crossplane.io/v1alpha1
kind: Grant
metadata:
  name: grant-owner-role-privilege-connect
spec:
  deletionPolicy:  Orphan
  forProvider:
    withOption: "GRANT"
    privileges:
      - CONNECT
    roleRef:
      name: "ownerrole"
    databaseRef:
      name: "db1"
    revokePublicOnDb: true
---
apiVersion: postgresql.sql.crossplane.io/v1alpha1
kind: Grant
metadata:
  name: example-grant-role-1-on-schema
spec:
  forProvider:
    privileges:
      - ALL
    withOption: GRANT
    roleRef:
      name: no-grants-role
    databaseRef:
      name: example
    schemaRef:
      name: my-schema
---
apiVersion: postgresql.sql.crossplane.io/v1alpha1
kind: Grant
metadata:
  name: example-grant-role-1-on-table
spec:
  forProvider:
    privileges:
      - SELECT
      - INSERT
    roleRef:
      name: no-grants-role
    databaseRef:
      name: db1
    schemaRef:
      name: public
    tables:
      - test_table
---
apiVersion: postgresql.sql.crossplane.io/v1alpha1
kind: Grant
metadata:
  name: example-grant-role-1-on-sequence
spec:
  forProvider:
    privileges:
      - ALL
    roleRef:
      name: no-grants-role
    databaseRef:
      name: db1
    schemaRef:
      name: public
    sequences:
      - test_sequence
---
apiVersion: postgresql.sql.crossplane.io/v1alpha1
kind: Grant
metadata:
  name: example-grant-role-1-on-routine
spec:
  forProvider:
    privileges:
      - ALL
    roleRef:
      name: no-grants-role
    databaseRef:
      name: db1
    schemaRef:
      name: public
    routines:
      - name: test_procedure
        args:
        - TEXT
---
apiVersion: postgresql.sql.crossplane.io/v1alpha1
kind: Grant
metadata:
  name: example-grant-role-1-on-column
spec:
  forProvider:
    privileges:
      - UPDATE
    roleRef:
      name: no-grants-role
    databaseRef:
      name: db1
    schemaRef:
      name: public
    tables:
      - test_table_column
    columns:
      - test_column
---
apiVersion: postgresql.sql.crossplane.io/v1alpha1
kind: Grant
metadata:
  name: example-grant-role-1-on-foreign-data-wrapper
spec:
  forProvider:
    privileges:
      - USAGE
    roleRef:
      name: no-grants-role
    databaseRef:
      name: db1
    foreignDataWrappers:
      - test_foreign_data_wrapper
---
apiVersion: postgresql.sql.crossplane.io/v1alpha1
kind: Grant
metadata:
  name: example-grant-role-1-on-foreign-server
spec:
  forProvider:
    privileges:
      - USAGE
    roleRef:
      name: no-grants-role
    databaseRef:
      name: db1
    foreignServers:
      - test_foreign_server