apiVersion: postgresql.sql.crossplane.io/v1alpha1
kind: Role
metadata:
  name: example-role
spec:
  forProvider:
    connectionLimit: 10
    privileges:
      login: true
      createDb: true
  writeConnectionSecretToRef:
    name: example-role-secret
    namespace: default
