apiVersion: postgresql.sql.crossplane.io/v1alpha1
kind: Role
metadata:
  name: parent-role
spec:
  forProvider:
    connectionLimit: 10
    privileges:
      login: true
    configurationParameters:
      - name: 'statement_timeout'
        value: '123'
      - name: 'search_path'
        value: '"$user",public'

  writeConnectionSecretToRef:
    name: example-parent-role-secret
    namespace: default
---
apiVersion: postgresql.sql.crossplane.io/v1alpha1
kind: Role
metadata:
  name: example-role
spec:
  forProvider:
    privileges:
      createDb: true
  writeConnectionSecretToRef:
    name: example-role-secret
    namespace: default
