apiVersion: postgresql.sql.crossplane.io/v1alpha1
kind: Schema
metadata:
  name: my-schema
spec:
  forProvider:
    databaseRef:
      name: example
    roleRef:
      name: example-role
  providerConfigRef:
    name: default
