apiVersion: postgresql.sql.m.crossplane.io/v1alpha1
kind: Database
metadata:
  name: example
  namespace: default
spec:
  forProvider: {}
---
apiVersion: postgresql.sql.m.crossplane.io/v1alpha1
kind: Database
metadata:
  name: db1
  namespace: default
spec:
  deletionPolicy: Orphan
  forProvider:
    allowConnections: true
    owner: "ownerrole"
---
apiVersion: postgresql.sql.m.crossplane.io/v1alpha1
kind: Database
metadata:
  name: db-observe
  namespace: default
spec:
  managementPolicies:
  - Observe
  forProvider: {}
