apiVersion: postgresql.sql.m.crossplane.io/v1alpha1
kind: Role
metadata:
  name: owner-role
  namespace: default
spec:
  forProvider:
    privileges:
      createDb: true
      login: true
      createRole: true
      inherit: true
  writeConnectionSecretToRef:
    name: owner-role-secret
  providerConfigRef:
    kind: ProviderConfig
    name: default
---
apiVersion: postgresql.sql.m.crossplane.io/v1alpha1
kind: Role
metadata:
  name: writer-role
  namespace: default
spec:
  forProvider:
    connectionLimit: 10
    privileges:
      login: true
  writeConnectionSecretToRef:
    name: writer-role-secret
  providerConfigRef:
    kind: ProviderConfig
    name: default
---
apiVersion: postgresql.sql.m.crossplane.io/v1alpha1
kind: Role
metadata:
  name: reader-role
  namespace: default
spec:
  forProvider:
    connectionLimit: 10
    privileges:
      login: true
  writeConnectionSecretToRef:
    name: reader-role-secret
  providerConfigRef:
    kind: ProviderConfig
    name: default
---
# When owner-role creates new tables, grant full DML to writer-role
apiVersion: postgresql.sql.m.crossplane.io/v1alpha1
kind: DefaultPrivileges
metadata:
  name: writer-tables
  namespace: default
spec:
  forProvider:
    objectType: table
    roleRef:
      name: writer-role
    targetRole: owner-role
    privileges:
      - SELECT
      - INSERT
      - UPDATE
      - DELETE
      - TRUNCATE
    schema: public
    databaseRef:
      name: example
  providerConfigRef:
    kind: ProviderConfig
    name: default
---
# When owner-role creates new functions, grant EXECUTE to writer-role
apiVersion: postgresql.sql.m.crossplane.io/v1alpha1
kind: DefaultPrivileges
metadata:
  name: writer-functions
  namespace: default
spec:
  forProvider:
    objectType: function
    roleRef:
      name: writer-role
    targetRole: owner-role
    privileges:
      - EXECUTE
    schema: public
    databaseRef:
      name: example
  providerConfigRef:
    kind: ProviderConfig
    name: default
---
# When owner-role creates new tables, grant SELECT to reader-role
apiVersion: postgresql.sql.m.crossplane.io/v1alpha1
kind: DefaultPrivileges
metadata:
  name: reader-tables
  namespace: default
spec:
  forProvider:
    objectType: table
    roleRef:
      name: reader-role
    targetRole: owner-role
    privileges:
      - SELECT
    schema: public
    databaseRef:
      name: example
  providerConfigRef:
    kind: ProviderConfig
    name: default
---
# When owner-role creates new functions, grant EXECUTE to reader-role
apiVersion: postgresql.sql.m.crossplane.io/v1alpha1
kind: DefaultPrivileges
metadata:
  name: reader-functions
  namespace: default
spec:
  forProvider:
    objectType: function
    roleRef:
      name: reader-role
    targetRole: owner-role
    privileges:
      - EXECUTE
    schema: public
    databaseRef:
      name: example
  providerConfigRef:
    kind: ProviderConfig
    name: default
