apiVersion: mssql.sql.crossplane.io/v1alpha1
kind: Grant
metadata:
  name: example-grant
spec:
  forProvider:
    permissions:
      # CONNECT permission is added by default when user created. So, make sure
      # to include it unless you are sure that you don't need it.
      - CONNECT
      - CREATE TABLE
      - INSERT
      - SELECT
    userRef:
      name: example-user-ad
    databaseRef:
      name: example-db-ad
