apiVersion: mysql.sql.crossplane.io/v1alpha1
kind: User
metadata:
  name: example-user
spec:
  forProvider:
    passwordSecretRef:
      name: example-pw
      namespace: default
      key: password
    resourceOptions:
      maxQueriesPerHour: 1000
      maxUpdatesPerHour: 1000
      maxConnectionsPerHour: 100
      maxUserConnections: 10
  writeConnectionSecretToRef:
    name: example-connection-secret
    namespace: default
