---
apiVersion: mssql.sql.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: default
spec:
  credentials:
    source: MSSQLConnectionSecret
    connectionSecretRef:
      namespace: crossplane-system
      name: conn-example-mssqlserver
